// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlgoritmoNReinas(arg1:Array<any>,arg2:number):Promise<void>;

export function CreateBoard(arg1:number):Promise<Array<any>>;

export function ValidarMovimiento(arg1:Array<any>,arg2:number,arg3:number):Promise<Array<any>>;
