// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlgoritmoNReinas(arg1, arg2) {
  return window['go']['main']['App']['AlgoritmoNReinas'](arg1, arg2);
}

export function CreateBoard(arg1) {
  return window['go']['main']['App']['CreateBoard'](arg1);
}
